/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RescueRouteImport } from './routes/rescue'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutionalIndexRouteImport } from './routes/institutional.index'
import { Route as SafeIdCodeRouteImport } from './routes/safe-id.$code'
import { Route as RescueCodeRouteImport } from './routes/rescue.$code'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as InstitutionalMatchesRouteImport } from './routes/institutional.matches'
import { Route as InstitutionalIntegrationsRouteImport } from './routes/institutional.integrations'
import { Route as InstitutionalAuditRouteImport } from './routes/institutional.audit'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueRoute = RescueRouteImport.update({
  id: '/rescue',
  path: '/rescue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalIndexRoute = InstitutionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionalRoute,
} as any)
const SafeIdCodeRoute = SafeIdCodeRouteImport.update({
  id: '/safe-id/$code',
  path: '/safe-id/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueCodeRoute = RescueCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => RescueRoute,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalMatchesRoute = InstitutionalMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => InstitutionalRoute,
} as any)
const InstitutionalIntegrationsRoute =
  InstitutionalIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => InstitutionalRoute,
  } as any)
const InstitutionalAuditRoute = InstitutionalAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => InstitutionalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/institutional': typeof InstitutionalRouteWithChildren
  '/modes': typeof ModesRoute
  '/report': typeof ReportRoute
  '/rescue': typeof RescueRouteWithChildren
  '/search': typeof SearchRoute
  '/institutional/audit': typeof InstitutionalAuditRoute
  '/institutional/integrations': typeof InstitutionalIntegrationsRoute
  '/institutional/matches': typeof InstitutionalMatchesRoute
  '/person/$id': typeof PersonIdRoute
  '/rescue/$code': typeof RescueCodeRoute
  '/safe-id/$code': typeof SafeIdCodeRoute
  '/institutional/': typeof InstitutionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/modes': typeof ModesRoute
  '/report': typeof ReportRoute
  '/rescue': typeof RescueRouteWithChildren
  '/search': typeof SearchRoute
  '/institutional/audit': typeof InstitutionalAuditRoute
  '/institutional/integrations': typeof InstitutionalIntegrationsRoute
  '/institutional/matches': typeof InstitutionalMatchesRoute
  '/person/$id': typeof PersonIdRoute
  '/rescue/$code': typeof RescueCodeRoute
  '/safe-id/$code': typeof SafeIdCodeRoute
  '/institutional': typeof InstitutionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/institutional': typeof InstitutionalRouteWithChildren
  '/modes': typeof ModesRoute
  '/report': typeof ReportRoute
  '/rescue': typeof RescueRouteWithChildren
  '/search': typeof SearchRoute
  '/institutional/audit': typeof InstitutionalAuditRoute
  '/institutional/integrations': typeof InstitutionalIntegrationsRoute
  '/institutional/matches': typeof InstitutionalMatchesRoute
  '/person/$id': typeof PersonIdRoute
  '/rescue/$code': typeof RescueCodeRoute
  '/safe-id/$code': typeof SafeIdCodeRoute
  '/institutional/': typeof InstitutionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/institutional'
    | '/modes'
    | '/report'
    | '/rescue'
    | '/search'
    | '/institutional/audit'
    | '/institutional/integrations'
    | '/institutional/matches'
    | '/person/$id'
    | '/rescue/$code'
    | '/safe-id/$code'
    | '/institutional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/modes'
    | '/report'
    | '/rescue'
    | '/search'
    | '/institutional/audit'
    | '/institutional/integrations'
    | '/institutional/matches'
    | '/person/$id'
    | '/rescue/$code'
    | '/safe-id/$code'
    | '/institutional'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/institutional'
    | '/modes'
    | '/report'
    | '/rescue'
    | '/search'
    | '/institutional/audit'
    | '/institutional/integrations'
    | '/institutional/matches'
    | '/person/$id'
    | '/rescue/$code'
    | '/safe-id/$code'
    | '/institutional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InstitutionalRoute: typeof InstitutionalRouteWithChildren
  ModesRoute: typeof ModesRoute
  ReportRoute: typeof ReportRoute
  RescueRoute: typeof RescueRouteWithChildren
  SearchRoute: typeof SearchRoute
  PersonIdRoute: typeof PersonIdRoute
  SafeIdCodeRoute: typeof SafeIdCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue': {
      id: '/rescue'
      path: '/rescue'
      fullPath: '/rescue'
      preLoaderRoute: typeof RescueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional/': {
      id: '/institutional/'
      path: '/'
      fullPath: '/institutional/'
      preLoaderRoute: typeof InstitutionalIndexRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/safe-id/$code': {
      id: '/safe-id/$code'
      path: '/safe-id/$code'
      fullPath: '/safe-id/$code'
      preLoaderRoute: typeof SafeIdCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue/$code': {
      id: '/rescue/$code'
      path: '/$code'
      fullPath: '/rescue/$code'
      preLoaderRoute: typeof RescueCodeRouteImport
      parentRoute: typeof RescueRoute
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional/matches': {
      id: '/institutional/matches'
      path: '/matches'
      fullPath: '/institutional/matches'
      preLoaderRoute: typeof InstitutionalMatchesRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/institutional/integrations': {
      id: '/institutional/integrations'
      path: '/integrations'
      fullPath: '/institutional/integrations'
      preLoaderRoute: typeof InstitutionalIntegrationsRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/institutional/audit': {
      id: '/institutional/audit'
      path: '/audit'
      fullPath: '/institutional/audit'
      preLoaderRoute: typeof InstitutionalAuditRouteImport
      parentRoute: typeof InstitutionalRoute
    }
  }
}

interface InstitutionalRouteChildren {
  InstitutionalAuditRoute: typeof InstitutionalAuditRoute
  InstitutionalIntegrationsRoute: typeof InstitutionalIntegrationsRoute
  InstitutionalMatchesRoute: typeof InstitutionalMatchesRoute
  InstitutionalIndexRoute: typeof InstitutionalIndexRoute
}

const InstitutionalRouteChildren: InstitutionalRouteChildren = {
  InstitutionalAuditRoute: InstitutionalAuditRoute,
  InstitutionalIntegrationsRoute: InstitutionalIntegrationsRoute,
  InstitutionalMatchesRoute: InstitutionalMatchesRoute,
  InstitutionalIndexRoute: InstitutionalIndexRoute,
}

const InstitutionalRouteWithChildren = InstitutionalRoute._addFileChildren(
  InstitutionalRouteChildren,
)

interface RescueRouteChildren {
  RescueCodeRoute: typeof RescueCodeRoute
}

const RescueRouteChildren: RescueRouteChildren = {
  RescueCodeRoute: RescueCodeRoute,
}

const RescueRouteWithChildren =
  RescueRoute._addFileChildren(RescueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InstitutionalRoute: InstitutionalRouteWithChildren,
  ModesRoute: ModesRoute,
  ReportRoute: ReportRoute,
  RescueRoute: RescueRouteWithChildren,
  SearchRoute: SearchRoute,
  PersonIdRoute: PersonIdRoute,
  SafeIdCodeRoute: SafeIdCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
