/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportRouteImport } from './routes/report'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonIdRouteImport } from './routes/person.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/institutional': typeof InstitutionalRoute
  '/report': typeof ReportRoute
  '/search': typeof SearchRoute
  '/person/$id': typeof PersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/institutional': typeof InstitutionalRoute
  '/report': typeof ReportRoute
  '/search': typeof SearchRoute
  '/person/$id': typeof PersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/institutional': typeof InstitutionalRoute
  '/report': typeof ReportRoute
  '/search': typeof SearchRoute
  '/person/$id': typeof PersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/institutional' | '/report' | '/search' | '/person/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/institutional' | '/report' | '/search' | '/person/$id'
  id:
    | '__root__'
    | '/'
    | '/institutional'
    | '/report'
    | '/search'
    | '/person/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstitutionalRoute: typeof InstitutionalRoute
  ReportRoute: typeof ReportRoute
  SearchRoute: typeof SearchRoute
  PersonIdRoute: typeof PersonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstitutionalRoute: InstitutionalRoute,
  ReportRoute: ReportRoute,
  SearchRoute: SearchRoute,
  PersonIdRoute: PersonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
