/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RescueRouteImport } from './routes/rescue'
import { Route as SearchRouteImport } from './routes/search'
import { Route as InstitutionalIndexRouteImport } from './routes/institutional.index'
import { Route as InstitutionalAcceptInviteRouteImport } from './routes/institutional.accept-invite'
import { Route as InstitutionalAuditRouteImport } from './routes/institutional.audit'
import { Route as InstitutionalInstitutionsRouteImport } from './routes/institutional.institutions'
import { Route as InstitutionalIntegrationsRouteImport } from './routes/institutional.integrations'
import { Route as InstitutionalMatchesRouteImport } from './routes/institutional.matches'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as RescueCodeRouteImport } from './routes/rescue.$code'
import { Route as SafeIdCodeRouteImport } from './routes/safe-id.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueRoute = RescueRouteImport.update({
  id: '/rescue',
  path: '/rescue',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalIndexRoute = InstitutionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionalRoute,
} as any)
const InstitutionalAcceptInviteRoute =
  InstitutionalAcceptInviteRouteImport.update({
    id: '/accept-invite',
    path: '/accept-invite',
    getParentRoute: () => InstitutionalRoute,
  } as any)
const InstitutionalAuditRoute = InstitutionalAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => InstitutionalRoute,
} as any)
const InstitutionalInstitutionsRoute =
  InstitutionalInstitutionsRouteImport.update({
    id: '/institutions',
    path: '/institutions',
    getParentRoute: () => InstitutionalRoute,
  } as any)
const InstitutionalIntegrationsRoute =
  InstitutionalIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => InstitutionalRoute,
  } as any)
const InstitutionalMatchesRoute = InstitutionalMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => InstitutionalRoute,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueCodeRoute = RescueCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => RescueRoute,
} as any)
const SafeIdCodeRoute = SafeIdCodeRouteImport.update({
  id: '/safe-id/$code',
  path: '/safe-id/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/institutional': typeof InstitutionalRouteWithChildren
  '/modes': typeof ModesRoute
  '/privacy': typeof PrivacyRoute
  '/protocols': typeof ProtocolsRoute
  '/report': typeof ReportRoute
  '/rescue': typeof RescueRouteWithChildren
  '/search': typeof SearchRoute
  '/institutional/accept-invite': typeof InstitutionalAcceptInviteRoute
  '/institutional/audit': typeof InstitutionalAuditRoute
  '/institutional/institutions': typeof InstitutionalInstitutionsRoute
  '/institutional/integrations': typeof InstitutionalIntegrationsRoute
  '/institutional/matches': typeof InstitutionalMatchesRoute
  '/person/$id': typeof PersonIdRoute
  '/rescue/$code': typeof RescueCodeRoute
  '/safe-id/$code': typeof SafeIdCodeRoute
  '/institutional/': typeof InstitutionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/modes': typeof ModesRoute
  '/privacy': typeof PrivacyRoute
  '/protocols': typeof ProtocolsRoute
  '/report': typeof ReportRoute
  '/rescue': typeof RescueRouteWithChildren
  '/search': typeof SearchRoute
  '/institutional/accept-invite': typeof InstitutionalAcceptInviteRoute
  '/institutional/audit': typeof InstitutionalAuditRoute
  '/institutional/institutions': typeof InstitutionalInstitutionsRoute
  '/institutional/integrations': typeof InstitutionalIntegrationsRoute
  '/institutional/matches': typeof InstitutionalMatchesRoute
  '/person/$id': typeof PersonIdRoute
  '/rescue/$code': typeof RescueCodeRoute
  '/safe-id/$code': typeof SafeIdCodeRoute
  '/institutional': typeof InstitutionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/institutional': typeof InstitutionalRouteWithChildren
  '/modes': typeof ModesRoute
  '/privacy': typeof PrivacyRoute
  '/protocols': typeof ProtocolsRoute
  '/report': typeof ReportRoute
  '/rescue': typeof RescueRouteWithChildren
  '/search': typeof SearchRoute
  '/institutional/accept-invite': typeof InstitutionalAcceptInviteRoute
  '/institutional/audit': typeof InstitutionalAuditRoute
  '/institutional/institutions': typeof InstitutionalInstitutionsRoute
  '/institutional/integrations': typeof InstitutionalIntegrationsRoute
  '/institutional/matches': typeof InstitutionalMatchesRoute
  '/person/$id': typeof PersonIdRoute
  '/rescue/$code': typeof RescueCodeRoute
  '/safe-id/$code': typeof SafeIdCodeRoute
  '/institutional/': typeof InstitutionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/institutional'
    | '/modes'
    | '/privacy'
    | '/protocols'
    | '/report'
    | '/rescue'
    | '/search'
    | '/institutional/accept-invite'
    | '/institutional/audit'
    | '/institutional/institutions'
    | '/institutional/integrations'
    | '/institutional/matches'
    | '/person/$id'
    | '/rescue/$code'
    | '/safe-id/$code'
    | '/institutional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/modes'
    | '/privacy'
    | '/protocols'
    | '/report'
    | '/rescue'
    | '/search'
    | '/institutional/accept-invite'
    | '/institutional/audit'
    | '/institutional/institutions'
    | '/institutional/integrations'
    | '/institutional/matches'
    | '/person/$id'
    | '/rescue/$code'
    | '/safe-id/$code'
    | '/institutional'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/institutional'
    | '/modes'
    | '/privacy'
    | '/protocols'
    | '/report'
    | '/rescue'
    | '/search'
    | '/institutional/accept-invite'
    | '/institutional/audit'
    | '/institutional/institutions'
    | '/institutional/integrations'
    | '/institutional/matches'
    | '/person/$id'
    | '/rescue/$code'
    | '/safe-id/$code'
    | '/institutional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  InstitutionalRoute: typeof InstitutionalRouteWithChildren
  ModesRoute: typeof ModesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProtocolsRoute: typeof ProtocolsRoute
  ReportRoute: typeof ReportRoute
  RescueRoute: typeof RescueRouteWithChildren
  SearchRoute: typeof SearchRoute
  PersonIdRoute: typeof PersonIdRoute
  SafeIdCodeRoute: typeof SafeIdCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue': {
      id: '/rescue'
      path: '/rescue'
      fullPath: '/rescue'
      preLoaderRoute: typeof RescueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional/': {
      id: '/institutional/'
      path: '/'
      fullPath: '/institutional/'
      preLoaderRoute: typeof InstitutionalIndexRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/institutional/accept-invite': {
      id: '/institutional/accept-invite'
      path: '/accept-invite'
      fullPath: '/institutional/accept-invite'
      preLoaderRoute: typeof InstitutionalAcceptInviteRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/institutional/audit': {
      id: '/institutional/audit'
      path: '/audit'
      fullPath: '/institutional/audit'
      preLoaderRoute: typeof InstitutionalAuditRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/institutional/institutions': {
      id: '/institutional/institutions'
      path: '/institutions'
      fullPath: '/institutional/institutions'
      preLoaderRoute: typeof InstitutionalInstitutionsRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/institutional/integrations': {
      id: '/institutional/integrations'
      path: '/integrations'
      fullPath: '/institutional/integrations'
      preLoaderRoute: typeof InstitutionalIntegrationsRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/institutional/matches': {
      id: '/institutional/matches'
      path: '/matches'
      fullPath: '/institutional/matches'
      preLoaderRoute: typeof InstitutionalMatchesRouteImport
      parentRoute: typeof InstitutionalRoute
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue/$code': {
      id: '/rescue/$code'
      path: '/$code'
      fullPath: '/rescue/$code'
      preLoaderRoute: typeof RescueCodeRouteImport
      parentRoute: typeof RescueRoute
    }
    '/safe-id/$code': {
      id: '/safe-id/$code'
      path: '/safe-id/$code'
      fullPath: '/safe-id/$code'
      preLoaderRoute: typeof SafeIdCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InstitutionalRouteChildren {
  InstitutionalAcceptInviteRoute: typeof InstitutionalAcceptInviteRoute
  InstitutionalAuditRoute: typeof InstitutionalAuditRoute
  InstitutionalInstitutionsRoute: typeof InstitutionalInstitutionsRoute
  InstitutionalIntegrationsRoute: typeof InstitutionalIntegrationsRoute
  InstitutionalMatchesRoute: typeof InstitutionalMatchesRoute
  InstitutionalIndexRoute: typeof InstitutionalIndexRoute
}

const InstitutionalRouteChildren: InstitutionalRouteChildren = {
  InstitutionalAcceptInviteRoute: InstitutionalAcceptInviteRoute,
  InstitutionalAuditRoute: InstitutionalAuditRoute,
  InstitutionalInstitutionsRoute: InstitutionalInstitutionsRoute,
  InstitutionalIntegrationsRoute: InstitutionalIntegrationsRoute,
  InstitutionalMatchesRoute: InstitutionalMatchesRoute,
  InstitutionalIndexRoute: InstitutionalIndexRoute,
}

const InstitutionalRouteWithChildren = InstitutionalRoute._addFileChildren(
  InstitutionalRouteChildren,
)

interface RescueRouteChildren {
  RescueCodeRoute: typeof RescueCodeRoute
}

const RescueRouteChildren: RescueRouteChildren = {
  RescueCodeRoute: RescueCodeRoute,
}

const RescueRouteWithChildren =
  RescueRoute._addFileChildren(RescueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  InstitutionalRoute: InstitutionalRouteWithChildren,
  ModesRoute: ModesRoute,
  PrivacyRoute: PrivacyRoute,
  ProtocolsRoute: ProtocolsRoute,
  ReportRoute: ReportRoute,
  RescueRoute: RescueRouteWithChildren,
  SearchRoute: SearchRoute,
  PersonIdRoute: PersonIdRoute,
  SafeIdCodeRoute: SafeIdCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
